Repository KingSand08/LikeHome, pull requests merged in 2024-09, with the labels that each got.

#31 Set up initial page structure
  app/bookings/[id]/page.tsx
  app/bookings/page.tsx
  app/page.tsx
  app/profile/page.tsx
  app/reserve/[id]/page.tsx
Labels: process

#32 Update next.js to 14.2.12. Modify npm run dev for one command install & run.
  .gitignore
  package-lock.json
  package.json
Labels: task-process, role-dev

#46 fix: Replace usage of next/router with the proper slug handling
  app/bookings/[id]/page.tsx
  app/reserve/[id]/page.tsx
Labels: task-process, role-dev

#50 Revert 32 dev experience - to fix preview and production vercel
  package-lock.json
  package.json
Labels: task-process, role-dev, role-release
