Repository KingSand08/LikeHome, pull requests merged in 2024-10, with the labels that each got.

#51 Footer and Header #13, #23
  app/layout.tsx
  app/page.tsx
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/layout/ThemeSwitch.tsx
  components/providers/providers.tsx
  package-lock.json
  package.json
  postcss.config.mjs
  public/stellarHorizons.png
  tailwind.config.ts
  tsconfig.json
Labels: task-requirement-MMF, role-frontend, user-navigation

#60 Refactors page structure
  app/[hotelID]/[roomID]/error.tsx
  app/[hotelID]/[roomID]/page.tsx
  app/[hotelID]/error.tsx
  app/[hotelID]/page.tsx
  app/bookings/[id]/error.tsx
  app/bookings/[id]/page.tsx
  app/page.tsx
  app/profile/page.tsx
  app/reserve/[id]/page.tsx
  components/ProfilePage/AccountInformation.tsx
  components/ProfilePage/Rewards.tsx
Labels: enhancement

#61 Auth V1 - OAuth with Google and Login page
  app/api/auth/[...nextauth]/route.ts
  app/api/auth/signin.js
  app/signin/page.tsx
  auth.ts
  components/OAuthButton.tsx
  components/layout/Header.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/icons/github.icon.png
  public/icons/google.icon.png
  public/icons/instagram.icon.png
  public/icons/meta.icon.png
  public/icons/x-twitter.icon.png
  public/likehome_form_icon.png
  types/next-auth.d.ts
Labels: task-requirement-MMF, user-authentication, user-navigation, user-UI/UX

#63 New OAuth Authentication, Profile Acknowledgement, and Dynamic Sign In/Out Button
  .vscode/settings.json
  app/api/auth/[...nextauth]/route.ts
  app/signin/page.tsx
  auth.ts
  components/OAuthButton.tsx
  components/SignOutButton.tsx
  components/layout/Header.tsx
  components/providers/providers.tsx
  middleware.ts
  package-lock.json
  package.json
  public/default-avatar.png
  tsconfig.json
Labels: task-requirement-MMF, role-frontend, role-backend, user-authentication, user-profile, v0.5.0

#1 Configure testing libraries and automated testing
  .github/workflow/codecoverage.yml
  __tests__/ExampleUI.test.tsx
  __tests__/ExampleUnit.test.tsx
  __tests__/__snapshots__/ExampleUI.test.tsx.snap
  __tests__/test-utils.tsx
  jest.config.ts
  package-lock.json
  package.json
Labels: task-process, role-dev

#2 Integrate Lint Work Flow
  .github/workflow/lint.yml
  package-lock.json
Labels: task-process

#67 Initial setup of Rapid Hotels.com API
  app/api/hotels/region/route.ts
  app/api/hotels/search/rooms/route.ts
  app/api/hotels/search/route.ts
  lib/rapid-hotel-api/api-setup.ts
  lib/rapid-hotel-api/validateDates.ts
  lib/rapid-hotel-api/validateDomainLocale.ts
  lib/rapid-hotel-api/validatePriceRange.ts
  types/rapid-hotels-api/api-json-docs/hotel-room-offers-doc.ts
  types/rapid-hotels-api/api-json-docs/hotels-region-doc.ts
  types/rapid-hotels-api/api-json-docs/hotels-search-doc.ts
  types/rapid-hotels-api/hotel-room-offers-types.ts
  types/rapid-hotels-api/hotel-search-types.ts
  types/rapid-hotels-api/region-search-types.ts
Labels: task-requirement-MMF, role-backend, user-reservations
