Repository KingSand08/LikeHome, pull requests merged in 2024-11, with the labels that each got.

#83 Auth Update
  app/(.)signin/page.tsx
  app/about/page.tsx
  app/favicon.ico
  app/signin/page.tsx
  auth.ts
  components/OAuthButton.tsx
  components/SignOutButton.tsx
  components/auth/Avatar.tsx
  components/auth/OAuthButton.tsx
  components/auth/OAuthButtonForm.tsx
  components/auth/SignOutButton.tsx
  components/auth/SigninButton.tsx
  components/auth/SigninPage.tsx
  components/buttons/CancelButton.tsx
  components/layout/Footer.tsx
  components/layout/Header.tsx
  components/modal/ModalRoute.tsx
  middleware.ts
  package-lock.json
  public/icons/app/likehome_form_icon.png
  public/icons/app/stellarHorizons.png
  public/icons/providers/discord.icon.png
  public/icons/providers/github.icon.png
  public/icons/providers/google.icon.png
  public/icons/providers/instagram.icon.png
  public/icons/providers/meta.icon.png
  public/icons/providers/x-twitter.icon.png
  types/ui/classChange.ts
Labels: role-backend, user-authentication, user-UI/UX

#104 Base Responsive UI/UX Overhaul (Profile Page, Application Theme, About Page, Sign-in Page, Nav Component, and Other)
  app/(.)signin/page.tsx
  app/(signed-in)/profile/ProfileContent.tsx
  app/(signed-in)/profile/page.tsx
  app/about/page.tsx
  app/layout.tsx
  app/signin/page.tsx
  app/styles/AnimatedBackground.module.css
  app/styles/globals.css
  components/ProfilePage/AccountInformation.tsx
  components/ProfilePage/ProfilePage.tsx
  components/about/contact-us.tsx
  components/auth/Avatar.tsx
  components/auth/SigninPage.tsx
  components/layout/Header.tsx
  components/modal/ModalRoute.tsx
  data/developers.json
  public/drop-down-btn.tsx
  public/images/team/Minh.jpg
  public/images/team/Minh.png
  public/next.svg
  public/patterns/dots-wave-animated.svg
  public/patterns/dots.svg
  public/vercel.svg
  tailwind.config.ts
  types/User.ts
Labels: task-requirement-MMF, user-navigation, user-UI/UX, user-profile

#112 Hotel Listing Page + Error Page + Loading Page - UI/UX + Modularization + Code Maintenance
  app/(.)signin/page.tsx
  app/hotels/[hotelId]/page.tsx
  app/signin/page.tsx
  app/styles/AnimatedLoadingText.module.scss
  app/test/page.tsx
  auth.ts
  components/HotelListing/HotelLocation.tsx
  components/HotelListing/PaginatedRoomImageGrid.tsx
  components/HotelListing/RoomImageCarousel.tsx
  components/HotelListing/RoomOffers.tsx
  components/modal/ImageModal.tsx
  components/modal/Modal.tsx
  components/ui/ErrorPage.tsx
  components/ui/LoadingPage.tsx
  components/ui/page.tsx
  next.config.mjs
  package-lock.json
  package.json
  public/animations/likehome-load.json
  public/animations/likehome-load.webm
  public/animations/patterns/dots-wave-animated.svg
  public/animations/patterns/dots.svg
  public/hotel.svg
  types/rapid-hotels-api/CompleteHotelInformation.ts
Labels: task-requirement-MMF, role-frontend, role-backend, user-navigation, user-UI/UX

#119 Mock references (with revised schema).
  app/api/hotels/region/route.ts
  prisma/schema.prisma
  server-actions/cache-actions.ts
Labels: blocked

#115 Mock
  app/api/hotels/region/route.ts
  app/hotels/[hotelId]/[roomId]/page.tsx
  components/search/HotelResults/HotelSelect.tsx
  components/ui/location-combobox.tsx
  prisma/schema.prisma
  server-actions/api-actions.ts
  server-actions/cache-actions.ts
  server-actions/region-actions.ts
Labels: blocker

#116 Redeem free stay
  app/(signed-in)/bookings/[bookingId]/page.tsx
  app/(signed-in)/bookings/page.tsx
  app/globals.css
  app/layout.tsx
  components/checkout/CheckoutConfirmation.tsx
  components/checkout/CheckoutInfo.tsx
  components/ui/rainbow-button.tsx
  lib/BookingFunctions.ts
  lib/rapid-hotel-api/api-setup.ts
  prisma/schema.prisma
  server-actions/reservation-actions.ts
  server-actions/user-actions.ts
  tailwind.config.ts
Labels: blocked
